export enum ApiRoute {
  REGISTER = 'account/Register',
  LOGIN = 'auth/Login',

  LIVRO_GETALL = 'livro',
  LIVRO_ID = 'livro/',
  LIVRO_AUTOR = 'livro/autor/',
  LIVRO_GENERO = 'livro/genero/',
  LIVRO_GENERO_DESCRIPTION = 'livro/genero/',
  LIVRO_TITULO = 'livro/titulo',
  LIVRO_SAVE = 'livro',
  LIVRO_DESCRIPTION = 'livro/description/',
  LIVRO_DELETE = 'livro/',
  GENEROS = 'livro/generos',

  ALUNO_GETALL = 'cliente',
  ALUNO_ID = 'cliente/',
  ALUNO_NOME = 'cliente/name/',
  ALUNO_CPF = 'cliente/cpf/',
  ALUNO_EMAIL = 'cliente/email/',
  ALUNO_SAVE = 'cliente',
  ALUNO_DESCRIPTION = 'cliente/description/',

  INSTITUICAO_GETALL = 'instituicao',
  INSTITUICAO_ID = 'instituicao/',
  INSTITUICAO_NOME = 'instituicao/name/',
  INSTITUICAO_CNPJ = 'instituicao/cnpj/',
  INSTITUICAO_DESCRIPTION = 'instituicao/description/',
  INSTITUICAO_SAVE = 'instituicao',

  EMPRESTIMO_ID = 'emprestimo/',
  EMPRESTIMO_GETALL = 'emprestimo',
  EMPRESTIMO_DESCRIPTION = 'emprestimo/description/',
  EMPRESTIMO_SAVE = 'emprestimo',
}